# Generated by Django 3.2.16 on 2023-01-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0003_detailtransaksi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='waktu',
            field=models.DateTimeField(),
        ),
    ]
