# Generated by Django 3.2.16 on 2023-01-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0005_auto_20230113_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
