# Generated by Django 3.2.16 on 2023-01-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0006_menu_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='total_item',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
