# Generated by Django 3.2.16 on 2023-01-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0007_transaksi_total_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtransaksi',
            name='harga',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
