# Generated by Django 3.2.16 on 2023-01-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0008_auto_20230114_1519'),
        ('kasir', '0008_detailtransaksi_harga'),
    ]

    operations = [
    ]
