# Generated by Django 3.2.16 on 2023-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0012_auto_20230116_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='waktu_selesai',
            field=models.DateTimeField(null=True),
        ),
    ]
